### ISSUE TITLE
[Question] How ListenerAdapter works with this Lib?

### ISSUE THREAD

**Issue by juferdinand** [viascom/aluna-spring-boot-starter#195]
Hey I searched and didnt found an way to register Listener for something like if Member join or leave.

Thanks for your help and time

Greetings
Justin

**Comment by itsmefox** [comment]
Hi,

There are three ways to register Listeners in Aluna. 
- The clean spring way is to make a class extend/implement `ListenerAdapter` or `CoroutineEventListener` and annotate it with, for example, `@Component` so that it is part of the Spring Context. Aluna will then register it for you during startup.
- The second way is to use Spring events as shown here: [OnEventHandler](https://github.com/viascom/discord-bot-spring-boot-starter/blob/0e7de235b7ff4e3b49d430517648e77a248902d0/src/test/kotlin/io/viascom/discord/bot/aluna/bot/OnEventHandler.kt#L32-L32). For this to work it is crucial that `aluna.discord.publish-events` is set to true. Also, make sure to check the other possible settings [here](https://github.com/viascom/discord-bot-spring-boot-starter/blob/0e7de235b7ff4e3b49d430517648e77a248902d0/src/main/kotlin/io/viascom/discord/bot/aluna/property/AlunaDiscordProperties.kt#L142-L169) as for bigger bots a lot of events are triggered which leads to higher memory usage.
- The third method is more manual: Injecting the ShardManager and then calling `addEventListener`. I would not recommend this, as depending on where you do this, the bot may already be connected, and you will lose events until you add your listener.

Examples of the member join event:

```kotlin
//With ListenerAdapter()
@Component
class EventLogListener : ListenerAdapter() {
    override fun onGuildMemberJoin(event: GuildMemberJoinEvent) {
        TODO("Add you code here")
    }
}


//With CoroutineEventListener
@Component
class CoEventLogListener : CoroutineEventListener {
    override suspend fun onEvent(event: GenericEvent) {
       when (event) {
            is GuildMemberJoinEvent -> onGuildMemberJoin(event)
            else -> {}
        }
    }

    private suspend fun onGuildMemberJoin(event: GuildMemberJoinEvent) {
        TODO("Add you code here")
    }
}

//With Spring events
@Component
class EventHandler {

    /*
    If aluna.discord.publish-events: true, all JDA events are published as Spring events.
    */
    @EventListener
    fun onGuildMemberJoin(event: GuildMemberJoinEvent) {
        TODO("Add you code here")
    }
}
```
